export const catalogServices = [
    // 10 Pets
    {
        _id: 'pet-01',
        name: 'Golden Retriever Puppy',
        category: 'Pets',
        price: 450,
        rating: 4.9,
        location: 'New York, NY',
        date: '2026-07-15',
        description: 'Friendly, intelligent, and highly energetic companion raised with family care. Fully vaccinated and health certified.',
        imgurl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-02',
        name: 'Persian Kitten',
        category: 'Pets',
        price: 350,
        rating: 4.8,
        location: 'Los Angeles, CA',
        date: '2026-07-16',
        description: 'Gentle, quiet cat with long fluffy fur and sweet demeanor. Litter-trained and microchipped.',
        imgurl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-03',
        name: 'French Bulldog',
        category: 'Pets',
        price: 500,
        rating: 5.0,
        location: 'Chicago, IL',
        date: '2026-07-14',
        description: 'Compact, muscular dog with cute bat ears and affectionate nature. Great for apartments.',
        imgurl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-04',
        name: 'Holland Lop Rabbit',
        category: 'Pets',
        price: 120,
        rating: 4.7,
        location: 'Houston, TX',
        date: '2026-07-18',
        description: 'Adorable floppy-eared bunny, friendly and great for indoor homes. Comes with starter hay.',
        imgurl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-05',
        name: 'Maine Coon Kitten',
        category: 'Pets',
        price: 400,
        rating: 4.9,
        location: 'Phoenix, AZ',
        date: '2026-07-12',
        description: 'Large, playful cat breed known for its gentle giant personality and tuition training.',
        imgurl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-06',
        name: 'Cockatiel Parakeet',
        category: 'Pets',
        price: 90,
        rating: 4.6,
        location: 'Philadelphia, PA',
        date: '2026-07-17',
        description: 'Vocal, affectionate pet bird with a cheerful crest and crest whistle ability.',
        imgurl: 'https://images.unsplash.com/photo-1522858547137-f1dcec554f55?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-07',
        name: 'German Shepherd Puppy',
        category: 'Pets',
        price: 480,
        rating: 4.9,
        location: 'San Antonio, TX',
        date: '2026-07-10',
        description: 'Loyal, protective, and highly intelligent working dog breed. Health guarantee included.',
        imgurl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-08',
        name: 'Scottish Fold Cat',
        category: 'Pets',
        price: 380,
        rating: 4.8,
        location: 'San Diego, CA',
        date: '2026-07-13',
        description: 'Calm cat with folded ears and large round expressive eyes. Very gentle demeanor.',
        imgurl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-09',
        name: 'Syrian Hamster',
        category: 'Pets',
        price: 35,
        rating: 4.5,
        location: 'Dallas, TX',
        date: '2026-07-19',
        description: 'Easy-to-care-for pocket pet, active and curious. Includes starter cage wheel.',
        imgurl: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },
    {
        _id: 'pet-10',
        name: 'Canary Bird',
        category: 'Pets',
        price: 65,
        rating: 4.7,
        location: 'San Jose, CA',
        date: '2026-07-11',
        description: 'Bright yellow singing bird, ideal for apartment living and cheerful atmosphere.',
        imgurl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=800&auto=format&fit=crop',
        email: 'adoption@warmpaws.com'
    },

    // 10 Food Items
    {
        _id: 'food-01',
        name: 'Royal Canin Adult Dry Kibble',
        category: 'Food',
        price: 42,
        rating: 4.9,
        location: 'WarmPaws Store',
        date: '2026-07-19',
        description: 'Tailored nutrition with essential high-grade protein for adult dogs to maintain muscle mass.',
        imgurl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-02',
        name: 'Whiskas Wet Salmon Pate in Gravy',
        category: 'Food',
        price: 24,
        rating: 4.8,
        location: 'WarmPaws Store',
        date: '2026-07-18',
        description: 'Moisture-rich delicious salmon meal packed with vitamins and omega-6 fatty acids for adult cats.',
        imgurl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-03',
        name: 'Pedigree Real Chicken & Rice Formula',
        category: 'Food',
        price: 38,
        rating: 4.7,
        location: 'WarmPaws Store',
        date: '2026-07-17',
        description: 'High-protein kibble supporting strong muscles, healthy digestion, and immune defense.',
        imgurl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-04',
        name: 'Purina Pro Plan Sensitive Skin Salmon',
        category: 'Food',
        price: 55,
        rating: 4.9,
        location: 'WarmPaws Store',
        date: '2026-07-16',
        description: 'Omega-rich formula designed specifically for pets with delicate skin and sensitive stomachs.',
        imgurl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-05',
        name: 'Timothy Hay Organic Bale (Rabbit)',
        category: 'Food',
        price: 18,
        rating: 4.8,
        location: 'WarmPaws Store',
        date: '2026-07-15',
        description: 'Premium fiber-dense organic forage essential for healthy rabbit digestion and dental health.',
        imgurl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-06',
        name: 'Temptations Crunchy Cat Treats',
        category: 'Food',
        price: 12,
        rating: 4.9,
        location: 'WarmPaws Store',
        date: '2026-07-14',
        description: 'Irresistible chicken-flavored crunchy treats under 2 calories each for daily rewards.',
        imgurl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-07',
        name: 'Zupreem Tropical Fruit Bird Pellets',
        category: 'Food',
        price: 22,
        rating: 4.6,
        location: 'WarmPaws Store',
        date: '2026-07-13',
        description: 'Balanced fruit-flavored daily diet enriched with essential vitamins for medium-sized birds.',
        imgurl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-08',
        name: 'Blue Buffalo Wilderness Duck Formula',
        category: 'Food',
        price: 62,
        rating: 5.0,
        location: 'WarmPaws Store',
        date: '2026-07-12',
        description: 'Grain-free deboned duck & sweet potato formula crafted for active dogs needing high energy.',
        imgurl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-09',
        name: 'Dental Chew Sticks (Beef Flavor)',
        category: 'Food',
        price: 15,
        rating: 4.8,
        location: 'WarmPaws Store',
        date: '2026-07-11',
        description: 'Removes plaque and freshens breath while your dog enjoys a savory beef chewing session.',
        imgurl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },
    {
        _id: 'food-10',
        name: 'Organic Puppy Growth Milk Replacer',
        category: 'Food',
        price: 28,
        rating: 4.7,
        location: 'WarmPaws Store',
        date: '2026-07-10',
        description: 'Nutrient-rich milk formula for newborn and weaning puppies to support bone and muscle growth.',
        imgurl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=800&auto=format&fit=crop',
        email: 'store@warmpaws.com'
    },

    // 10 Care Products
    {
        _id: 'care-01',
        name: 'Hypoallergenic Oatmeal Dog Shampoo',
        category: 'Care Products',
        price: 19,
        rating: 4.9,
        location: 'WarmPaws Care',
        date: '2026-07-19',
        description: 'Soothes dry, itchy skin with natural aloe vera & organic oatmeal. Free from harsh chemicals.',
        imgurl: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-02',
        name: 'Flea & Tick Prevention Topical Drops',
        category: 'Care Products',
        price: 32,
        rating: 4.8,
        location: 'WarmPaws Care',
        date: '2026-07-18',
        description: 'Fast-acting 30-day waterproof protection against fleas, ticks, and lice.',
        imgurl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-03',
        name: 'Enzymatic Dog Toothpaste & Brush Kit',
        category: 'Care Products',
        price: 16,
        rating: 4.7,
        location: 'WarmPaws Care',
        date: '2026-07-17',
        description: 'Fights tartar buildup, freshens breath, and supports gum health with tasty poultry flavor.',
        imgurl: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-04',
        name: 'De-Shedding Steel Slicker Brush',
        category: 'Care Products',
        price: 22,
        rating: 4.9,
        location: 'WarmPaws Care',
        date: '2026-07-16',
        description: 'Reduces shedding up to 95% by gently removing loose undercoat without damaging topcoat.',
        imgurl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-05',
        name: 'Ear Cleansing Solution with Aloe',
        category: 'Care Products',
        price: 14,
        rating: 4.8,
        location: 'WarmPaws Care',
        date: '2026-07-15',
        description: 'Gently cleanses dirt and earwax while preventing ear infections and itching.',
        imgurl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-06',
        name: 'Pet Nail Clipper with Safety Guard',
        category: 'Care Products',
        price: 12,
        rating: 4.6,
        location: 'WarmPaws Care',
        date: '2026-07-14',
        description: 'Precision stainless steel blades with an adjustable safety stop mechanism to avoid over-trimming.',
        imgurl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-07',
        name: 'Odor-Control Clumping Cat Litter',
        category: 'Care Products',
        price: 26,
        rating: 4.9,
        location: 'WarmPaws Care',
        date: '2026-07-13',
        description: 'Dust-free natural clay litter with 10-day odor neutralization power for multi-cat homes.',
        imgurl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-08',
        name: 'Paw Relief Conditioning Wax Balm',
        category: 'Care Products',
        price: 15,
        rating: 4.8,
        location: 'WarmPaws Care',
        date: '2026-07-12',
        description: 'Protects paw pads from hot pavement, ice, salt, and rough terrain while restoring moisture.',
        imgurl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-09',
        name: 'Stain & Odor Eliminator Enzymatic Spray',
        category: 'Care Products',
        price: 18,
        rating: 4.7,
        location: 'WarmPaws Care',
        date: '2026-07-11',
        description: 'Bio-enzymatic formula breaks down pet urine, vomit, and organic stains completely.',
        imgurl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },
    {
        _id: 'care-10',
        name: 'Calming Pheromone Diffuser Kit for Cats',
        category: 'Care Products',
        price: 34,
        rating: 4.9,
        location: 'WarmPaws Care',
        date: '2026-07-10',
        description: 'Clinically proven feline pheromones to reduce stress, scratching, and urine spraying.',
        imgurl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?q=80&w=800&auto=format&fit=crop',
        email: 'care@warmpaws.com'
    },

    // 10 Accessories
    {
        _id: 'acc-01',
        name: 'Orthopedic Memory Foam Pet Bed',
        category: 'Accessories',
        price: 65,
        rating: 4.9,
        location: 'WarmPaws Gear',
        date: '2026-07-19',
        description: 'Supports joints and pressure points for restorative sleep. Washable plush cover.',
        imgurl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-02',
        name: 'Adjustable No-Pull Mesh Dog Harness',
        category: 'Accessories',
        price: 25,
        rating: 4.8,
        location: 'WarmPaws Gear',
        date: '2026-07-18',
        description: 'Padded breathable chest harness preventing choking and pulling during daily walks.',
        imgurl: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-03',
        name: 'Multi-Level Cat Tree Tower Scratching Post',
        category: 'Accessories',
        price: 89,
        rating: 5.0,
        location: 'WarmPaws Gear',
        date: '2026-07-17',
        description: 'Features sisal-wrapped scratching posts, cozy plush hammock, and private condo hideout.',
        imgurl: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-04',
        name: 'Automatic Smart Pet Water Fountain',
        category: 'Accessories',
        price: 38,
        rating: 4.9,
        location: 'WarmPaws Gear',
        date: '2026-07-16',
        description: 'Ultra-quiet triple filtered water fountain encouraging pet hydration throughout the day.',
        imgurl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-05',
        name: 'Airline-Approved Soft-Sided Pet Carrier',
        category: 'Accessories',
        price: 45,
        rating: 4.8,
        location: 'WarmPaws Gear',
        date: '2026-07-15',
        description: 'Breathable mesh travel tote with fleece bedding for cats and small dogs up to 15 lbs.',
        imgurl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-06',
        name: 'Interactive Squeaky Plush Toy Set',
        category: 'Accessories',
        price: 18,
        rating: 4.7,
        location: 'WarmPaws Gear',
        date: '2026-07-14',
        description: 'Durable reinforced seams squeaky plush toys ideal for fetch, chewing, and cuddling.',
        imgurl: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-07',
        name: 'Heavy-Duty Retractable Dog Leash (16ft)',
        category: 'Accessories',
        price: 22,
        rating: 4.8,
        location: 'WarmPaws Gear',
        date: '2026-07-13',
        description: 'Tangle-free nylon tape leash with ergonomic handle and quick one-button locking brake.',
        imgurl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-08',
        name: 'Stainless Steel Double Food & Water Bowls',
        category: 'Accessories',
        price: 20,
        rating: 4.9,
        location: 'WarmPaws Gear',
        date: '2026-07-12',
        description: 'Non-slip silicon base prevents spills and tipping. Dishwasher-safe food-grade stainless steel.',
        imgurl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-09',
        name: 'Reflective Padded Leather Dog Collar',
        category: 'Accessories',
        price: 24,
        rating: 4.8,
        location: 'WarmPaws Gear',
        date: '2026-07-11',
        description: 'Genuine padded leather with 3M reflective stitching for maximum safety during night walks.',
        imgurl: 'https://images.unsplash.com/photo-1597843798223-2b2f32a764d2?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    },
    {
        _id: 'acc-10',
        name: 'Interactive Laser Pointer & Feather Teaser',
        category: 'Accessories',
        price: 15,
        rating: 4.7,
        location: 'WarmPaws Gear',
        date: '2026-07-10',
        description: 'USB rechargeable LED laser toy and feather wand keeping indoor cats active and entertained.',
        imgurl: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?q=80&w=800&auto=format&fit=crop',
        email: 'gear@warmpaws.com'
    }
];
